name: Angular LTS Update

on:
    schedule:
        - cron: '0 0 * * 0'
    workflow_dispatch:

jobs:
    check-and-update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Check for new Angular LTS
              id: check-lts
              run: |
                # Get current Angular version from package.json
                CURRENT_VERSION=$(node -e "console.log(require('./package.json').dependencies['@angular/core'])" | sed 's/[^0-9.]//g')
                echo "Current Angular version: $CURRENT_VERSION"
                
                # Get all available versions
                ALL_VERSIONS=$(npm view @angular/core versions --json | jq -r 'map(select(test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))) | sort_by(split(".") | map(tonumber))')
                
                # Extract current major version
                CURRENT_MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
                
                # Find all unique major versions above current
                MAJOR_UPGRADE_PATH=$(echo "$ALL_VERSIONS" | jq -r --argjson current_major "$CURRENT_MAJOR" 'map(split(".")[0] | tonumber) | unique | map(select(. > $current_major)) | @sh')
                
                if [ -n "$MAJOR_UPGRADE_PATH" ] && [ "$MAJOR_UPGRADE_PATH" != "''" ]; then
                  echo "update_available=true" >> $GITHUB_OUTPUT
                  echo "major_upgrade_path=$MAJOR_UPGRADE_PATH" >> $GITHUB_OUTPUT
                else
                  echo "No new major version available"
                  echo "update_available=false" >> $GITHUB_OUTPUT
                fi

            - name: Create update branch
              if: steps.check-lts.outputs.update_available == 'true'
              run: |
                git config --global user.name 'GitHub Actions Bot'
                git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                git checkout -b update/angular-multi-lts
        
            - name: Update Angular
              if: steps.check-lts.outputs.update_available == 'true'
              run: |
                set -e
                # Parse major upgrade path into array
                eval "MAJORS=(${{ steps.check-lts.outputs.major_upgrade_path }})"
                for NEXT_MAJOR in "${MAJORS[@]}"; do
                  echo "\n--- Upgrading to Angular major $NEXT_MAJOR ---\n"
                  npx @angular/cli@$NEXT_MAJOR update @angular/core@$NEXT_MAJOR @angular/cli@$NEXT_MAJOR --force
                  npx @angular/cli@$NEXT_MAJOR update @angular/material@$NEXT_MAJOR --force || true
                  npm install
                  git add .
                  git commit -m "Update Angular to major version $NEXT_MAJOR"
                done
                git push --set-upstream origin update/angular-multi-lts
                
            - name: Run tests
              if: false  # Tests are now run after each upgrade step
              run: echo "Tests run in upgrade loop"
                
            - name: Commit changes
              if: false  # Commits are now handled in the upgrade loop
              run: echo "Commits handled in upgrade loop"
                
            - name: Create Pull Request
              if: steps.check-lts.outputs.update_available == 'true'
              uses: peter-evans/create-pull-request@v5
              with:
                title: "Update Angular to latest LTS versions"
                body: |
                    This PR updates Angular through all available LTS versions above the current.
                    
                    ## Changes
                    - Updated @angular/core, @angular/cli, and @angular/material through all LTS versions
                    - Ran tests after each upgrade step
                    
                    Please review the changes carefully and test the application before merging.
                branch: update/angular-multi-lts
                base: main
                labels: "dependencies,angular-update"