name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: npm ci
      
      - name: Cypress run
        uses: cypress-io/github-action@v5.6.2
        with:
          install: true
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:4200'
          record: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}


