name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # check out all commits to get accurate created date
          fetch-depth: 0
        
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 16 # This allow Github Workflow running on node 16

      - name: Print Node version 
        run: node -v
      
      - name: Cypress run
        # best practices with specific version to mitigate unforeseen breaks
        uses: cypress-io/github-action@v5.6.2 
        with:
          # build appplication
          build: npm run build 
          # start application
          start: npm start 
          # wait until an app start
          wait-on: 'http://localhost:4200' 
          # this will record on cypress cloud
          record: true 
          # use component testing
          component: true 
        env:
          # cypress key
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


