name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # check out all commits to get accurate created date
          fetch-depth: 0
        
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 16 # This allow Github Workflow running on node 16

      - name: Print Node version 
        run: node -v
      
      - name: Cypress run
        uses: cypress-io/github-action@v5.6.2
        with:
          build: npm run build # build appplication
          start: npm start # start application
          wait-on: 'http://localhost:4200' # wait until an app start
          record: true # this will record on cypress cloud
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


