name: Manual Cypress Tests

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:          
  cypress-run:
    name: Cypress run
    environment: QA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 16 # This allow Github Workflow running on node 16
      
      - name: Cypress run
        # *best practices with specific version to mitigate unforeseen breaks
        uses: cypress-io/github-action@v5.6.2 
        with:
          browser: chrome
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
