name: Deploy to Prod

on:
  workflow_run:
    workflows: 
      - Deploy to Test
    types:
      - completed
    branches: 
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
