name: Deploy to Prod

on:
  workflow_run:
    workflows: 
      - Deploy Test
    types:
      - completed
    branches:
      - test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

      