name: Deploy Test

on:
  pull_request:
  push:
    branches: 
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 16 # This allow Github Workflow running on node 16

      - name: Print Node version 
        run: node -v
